version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '8000:80'
    env_file: .env
    depends_on:
      - db
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - '8501:8501'
    env_file: .env
    depends_on:
      - api
    volumes:
      - ./apps/streamlit:/app/apps/streamlit
      - ./core:/app/core
      - ./services:/app/services
  db:
    image: alpine:latest
    command: sleep infinity
    volumes:
      - ./data:/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
